// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jywjiivyvohojveoecat.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5d2ppaXZ5dm9ob2p2ZW9lY2F0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI3NTAzNjgsImV4cCI6MjA4ODMyNjM2OH0.Fyyajt5rcDKQKZeUTHPYVUg3uPOZxjhlR4RkuLObEjs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});